# Generated by Django 4.1.2 on 2022-10-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(choices=[('Herr', 'Herr'), ('Frau', 'Frau')], max_length=4, null=True)),
                ('name', models.CharField(max_length=50)),
                ('vorname', models.CharField(max_length=50)),
                ('geschlecht', models.CharField(choices=[('m', 'männlich'), ('w', 'weiblich'), ('d', 'diverse'), ('u', 'unbekannt')], max_length=1)),
                ('nationalitaet', models.CharField(max_length=30, null=True)),
                ('strasse', models.CharField(max_length=100)),
                ('plz', models.CharField(max_length=5)),
                ('ort', models.CharField(max_length=50)),
                ('geburtsdatum', models.DateField()),
                ('abteilung', models.CharField(max_length=50, null=True)),
                ('familienstand', models.CharField(choices=[('ledig', 'ledig'), ('verheiratet', 'verheiratet'), ('geschieden', 'geschieden')], max_length=11)),
                ('gehalt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iban', models.CharField(max_length=34)),
                ('steuerklasse', models.IntegerField()),
            ],
        ),
    ]
